### ISSUE TITLE
No B1+ bias correction applied to A maps (when PD white matter calibration is toggled off)?

### ISSUE THREAD

**Issue by Alfiew** [hMRI-group/hMRI-toolbox#100]
Hi, Apologies if this reveals some kind of naïvety on my part. 

I have created A maps using v0.5.0, by toggling 'hmri_def.PDproc.calibr' to 0. However when doing so, the output A map appears to have a strong B1+ bias, even though the log output states that B1+ correction has been applied. 

Is this a bug or am I missing something? Thanks. 

I've attached output QC images for a run with PD calibration (which looks fine), the run without calibration (with bias field visible in A map), and the logfile from the latter run. 

![A_map_QC](https://github.com/hMRI-group/hMRI-toolbox/assets/38325850/f20dfadb-fbd2-4d07-a4df-9f758168b024)
![PD_map_QC](https://github.com/hMRI-group/hMRI-toolbox/assets/38325850/4bd47717-53ff-4bcc-85c9-7fddc255866c)
[hMRI_map_creation_logfile.log](https://github.com/user-attachments/files/16113182/hMRI_map_creation_logfile.log)

**Comment by lukeje** [comment]
What you're seeing is receive bias (B1-), not transmit bias (B1+). There is an extra step during the PD calibration that removes the B1- using SPM's unified segmentation, and this does not happen when `hmri_def.PDproc.calibr = 0`, as the assumption is that in that case you would want the absolute signal intensities.

**Comment by Alfiew** [comment]
I see, thanks. In my case, I'm toying with different calibrations, so I still need bias-correction. 

I assume the bias-correction is applied prior to the calibration?

**Comment by lukeje** [comment]
For the bias correction, you can use SPM's unified segmentation tool yourself; you can turn off the segmentation output if you are not interested in having it.

**Comment by Alfiew** [comment]
Got it, thanks both for your help!
