### ISSUE TITLE
inverse deformation not moved to output folder after unified segmentation

### ISSUE THREAD

**Issue by JoeZiminski** [hMRI-group/hMRI-toolbox#14]
Dear hMRI team,

Just a small thing, the inverse deformation field is not moved to the specified output directory after unified segmentation, requires adding the regexp '^iy_.*\.nii$'  to line 80 of hmri_run_proc_US().

Best Wishes,
Joe

**Comment by halirutan** [comment]
@ChristophePhillips It appears that you implemented this part. Would you be able to have a look at this?
