### ISSUE TITLE
Old-vs-new version of SPM functions in hMRI

### ISSUE THREAD

**Issue by ChristophePhillips** [hMRI-group/hMRI-toolbox#15]
I stumbled on a small problem with some personal code: the version of some SPM functions distributed with hMRI is outdated. This made my code crash depending on the version of the function that was (higher) on the path. Since the hMRI folder, incl. subfolders, is added to the Matlab path when SPM initializes its toolboxes, hMRI versions of SPM functions are pushed to the top of the path tree (or at least higher than those of SPM). So Matlab can behave differently with/without launching SPM!

My sole example of out of date function so far is `spm_jsonwrite.m`:
- in the current public version of [SPM](https://github.com/spm/spm12/blob/3085dac00ac804adb190a7e82c6ef11866c8af02/spm_jsonwrite.m#L27), 
`% $Id: spm_jsonwrite.m 7526 2019-02-06 14:33:18Z guillaume $`
- in [hMRI](https://github.com/hMRI-group/hMRI-toolbox/blob/8dea911bbe731083e0cd1f7801f09b8bd4a7a601/spm12/spm_jsonwrite.m#L25),
`% $Id: spm_jsonwrite.m 7373 2018-07-09 16:57:21Z guillaume $`

I assume hMRI uses the older functionalities of `spm_jsonwrite.m` but other people's code, like mine, could be depending on the latest update. 

Since SPM12 is available on Github too, see [here](https://github.com/spm/spm12), would there be away to either sync hMRI's SPM functions with their source or simply remove those functions from the hMRI distribution if they are now part of SPM12 public version? Typically Guillaume ensures back compatibility, so this should not affect hMRI.

**Comment by DerOrfa** [comment]
I'd say remove them. 
I'm generally not a fan of code duplication and I guess we don't really need to support older SPM versions anyway.

**Comment by nbeliy** [comment]
I have same issue. Is it possible to not add paths recursively, or at least add spm paths if there no spm installed?
