### ISSUE TITLE
Possible bug in calculation of B1 maps with SE/STE EPI

### ISSUE THREAD

**Issue by nbeliy** [hMRI-group/hMRI-toolbox#26]
Hi all,  looking in the code of `hmri_create_b1map.m` I stumbled on a
[weird line 249](https://github.com/hMRI-group/hMRI-toolbox/blob/4bdc60004474d9f63ed6ccf53d69dfbd8fb16593/hmri_create_b1map.m#L249):

```matlab
B = spm_matrix([0 0 -p 0 0 0 1 1 1]);
...
M = inv(B*inv(V(1).mat)*V(1).mat); %#ok<*MINV>
```

Mathematically it doesn't make sense -- it is just equivalent to <img src="https://render.githubusercontent.com/render/math?math=BV^{-1}V = B">, 
shouldn't it be <img src="https://render.githubusercontent.com/render/math?math=V^{-1}BV = B^{-1}"> ,
in other word applying same rotation to B as for images?

```matlab
B = spm_matrix([0 0 -p 0 0 0 1 1 1]);
...
M = inv(inv(V(1).mat)*B*V(1).mat);
```

If it is a bug, it here for at least 7 years, which is worrying.

**Comment by lukeje** [comment]
Thank you for bringing this to our attention.

We have checked, and found this is not a bug, but just a specific programming paradigm taken from SPM. We are preparing a release which unifies how we read in data which will make this code a lot clearer.

**Comment by lukeje** [comment]
As promised, I have used the new utility function hmri_read_vols to simplify this piece of code and hopefully make it less confusing ([dea8ce5](https://github.com/hMRI-group/hMRI-toolbox/commit/dea8ce54e65b3a4fbaeeba11a1e0b579591c556a))
