### ISSUE TITLE
Problem with B1+ calculation

### ISSUE THREAD

**Issue by franciscofritz** [hMRI-group/hMRI-toolbox#34]
Dear all,
I just downloaded the last version of the hMRI toolbox and I found the following problem. I loaded the corresponding B1+ (using mfc_seste_... sequence) and B0 (using gre_3mm_... sequence) files, and it complains in the next line of the hmri_create_b1map.m, line 250 (indicated in the next text block in **bold**):
%-Loop over planes computing result Y
%-----------------------------------------------------------------------
clear Temp_mat;
corr_fact = exp(b1map_params.b1acq.TM/b1map_params.b1proc.T1);
for p = 1:V(1).dim(3) %loop over the partition dimension of the data set
    B = spm_matrix([0 0 -p 0 0 0 1 1 1]);
    for i = 1:n/2
        M = inv(B*inv(V(1).mat)*V(1).mat); %#ok<*MINV>
       **Y_tmptmp(:,:,((i-1)*2+1))  = real( ...
            acos(corr_fact*spm_slice_vol(V((i-1)*2+2),M,V(1).dim(1:2),0) ./ ...
            (spm_slice_vol(V((i-1)*2+1),M,V(1).dim(1:2),0)+b1map_params.b1proc.eps))/pi*180/b1map_params.b1acq.beta(i) ...
            ); % nearest neighbor interpolation**
        Y_tmptmp(:,:,((i-1)*2+2))  = 180/b1map_params.b1acq.beta(i) - Y_tmptmp(:,:,((i-1)*2+1));
        Temp_mat(:,:,i) = spm_slice_vol(V((i-1)*2+1),M,V(1).dim(1:2),0); %#ok<*AGROW>
    end 
(...)
%-------------------------------------------------------------------------------
The B1+ volumes acquired are 48x64x48x11 in size. Here comes the question, assuming that the acos() is being applied per slice but the b1map_params.b1acq.beta(i) is along the 4th dimension, shouldn't be an extra loop somewhere that goes through this dimension, or at least n = 22 to match the number of beta? Or, unless I am unaware of it, beta values most be equal to the number of slices acquired? In that sense, the sequence would be a black box (because how to estimate such if it is not informed or not possible modifiable in the sequence parameters).

Thanks,
Frank 

PS: It is not the first time having this problem, and it has been discussed previously with one of the toolbox-responsibles about it.

**Comment by lukeje** [comment]
Hey Frank, we recently modified the B1 mapping routine to add in some error checking: https://github.com/hMRI-group/hMRI-toolbox/blob/2c55bb3d6569bf643bfb66b68502cfb4d8446687/hmri_create_b1map.m#L226-L233
This will hopefully flag up to people in future that the number of volumes they provided does not match the number of angles.

Would this have helped you? Or do you have another suggestion?
