### ISSUE TITLE
Unwarping 3D-EPI B1 map fails for negative PE direction

### ISSUE THREAD

**Issue by lukeje** [hMRI-group/hMRI-toolbox#35]
For Siemens DICOMs, "blipdir" is read from the PhaseEncodingDirectionPositive DICOM header field. This parameter is then passed into the FieldMap toolbox. However, for a negative phase encoding direction, the Siemens definition of PhaseEncodingDirectionPositive (=0) is not appropriate for the FieldMap toolbox, which expects "-1". This results in a B1map that has not been unwarped and an empty B1ref.

This can probably be fixed here: 
https://github.com/hMRI-group/hMRI-toolbox/blob/2c55bb3d6569bf643bfb66b68502cfb4d8446687/hmri_create_b1map.m#L704-L709

**Comment by mfcallaghan** [comment]
Fixed by #36
