### ISSUE TITLE
parfor wsl1 

### ISSUE THREAD

**Issue by SherS2** [hMRI-group/hMRI-toolbox#52]
@lukeje 
It would be great if we could have a tag option in the default file to select the parfor.  

https://github.com/hMRI-group/hMRI-toolbox/blob/1a142ef14d62d265f512bbd5c45a878f9bbab290/hmri_calc_R2s.m#L143
https://github.com/hMRI-group/hMRI-toolbox/blob/1a142ef14d62d265f512bbd5c45a878f9bbab290/hmri_calc_R2s.m#L172

1. disabling 'parfor' required while running the toolbox in a cluster or container
2. It would be more useful to add an option to specify the 'number of core/thread' .

**Comment by SherS2** [comment]
There is not much time difference between 'parfor' and 'for' for the wls1. I want to launch multiple subjects simultaneously rather than allocating the par for this function.  Having an option in the default file is more suitable than editing the files in the hMRI-toolbox folder.

**Comment by SherS2** [comment]
size(y,2)  =  155064
-----------------------
tic
for n=1:size(y,2)
            beta(:,n)=WLS(logy(:,n),D,y0(:,n),niter);
        end
toc
Elapsed time is 1.026890 seconds.
------------------------------------------------------------

tic
parfor n=1:size(y,2)
beta(:,n)=WLS(logy(:,n),D,y0(:,n),niter);
end
toc
Starting parallel pool (parpool) using the 'local' profile ...
Preserving jobs with IDs: 660 because they contain crash dump files.
You can use 'delete(myCluster.Jobs)' to remove all jobs created with profile local. To create 'myCluster' use 'myCluster = parcluster('local')'.
Connected to the parallel pool (number of workers: 3).
Elapsed time is 15.956204 seconds.
------------------------------------------------------------

**Comment by lukeje** [comment]
It looks like your profiling is including the time taken to open the `parpool`. It also looks like Matlab is having trouble opening the it, as the warning about "crash dump files" is not normal. Note, however, that opening the `parpool` only needs to happen once (usually for the first slice) and so the acceleration for other slices will be greater.

If you want to disable the parallel pool, then (from [here](https://mathworks.com/matlabcentral/answers/158300-how-to-stop-parfor-from-launching-a-parallel-pool-automatically)), you can add
```matlab
ps = parallel.Settings;
ps.Pool.AutoCreate = false;
```
to your run scripts to avoid opening a parallel pool.
