### ISSUE TITLE
hMRI_map_creation_quality_assessment.json files are not readable with jsonread

### ISSUE THREAD

**Issue by VasilisKarlaftis** [hMRI-group/hMRI-toolbox#7]
This issue comes from the extra lines added in the spm function spm_jsonwrite.m: 206-211, whereas the original spm function has only the line 207. These extra lines result in an extra comma (,) before the bracket ] for both "MT2PD" and "T12PD" variables. Since there is no number or new variable following the last comma, the jsonread function returns with an error.

**Comment by tleutritz-cbs** [comment]
apparently this seems to be a specific SPM bug, as I can't realise the same behaviour with SPM12 r6906. Which version do you use?

**Comment by VasilisKarlaftis** [comment]
I am using SPM v7219. So basically the change I had to make in the spm_jsonwrite file of the hMRI toolbox was to comment out the lines 206 and 208-211.

**Comment by tleutritz-cbs** [comment]
I see (just had an older version of spm_jsonwrite in my repo...
So you're right, these lines seem to introduce the error.

**Comment by tleutritz-cbs** [comment]
this is now fixed with commit 6b1c7a8293af785d606f3b241c81bb74372444e8
so you can get the latest version [here](https://github.com/hMRI-group/hMRI-toolbox/archive/master.zip)
