### ISSUE TITLE
Issue with B1 bias correction with 3D EPI images 

### ISSUE THREAD

**Issue by julfou81** [hMRI-group/hMRI-toolbox#81]
Thank you very much for providing such a complete tool from acquisition to post-processing MPM images!

We ran into an issue linked to B1 bias correction on 7 subjects out of 11, even if the acquisition is the same for all subjects and the input images look similar.

We are using a Siemens Prisma 3T scanner and we use the sequence `mfc_seste_b1map_v1f`and we follow the settings of the customized SIEMENS 1mm protocol.

Here is an exemple of a subject for which the processing gives wrong results:
- input 3D images:
![check_inputs_001_jet](https://github.com/hMRI-group/hMRI-toolbox/assets/32452352/25c77dbd-e329-4932-8bfa-e3f3d951ed94)

- created B1+ map: 
<img width="779" alt="Capture d’écran 2023-09-20 à 17 45 32" src="https://github.com/hMRI-group/hMRI-toolbox/assets/32452352/25a188bf-3f29-421b-aa13-6377ed37b23a">

- MPM maps:
![check_maps_001_jet](https://github.com/hMRI-group/hMRI-toolbox/assets/32452352/7634d861-0a7a-490b-a7a0-f47e2045bcf8)

And below is an example of a subject which looks fine:
- input 3D images:
![check_inputs_002_jet](https://github.com/hMRI-group/hMRI-toolbox/assets/32452352/25f38ce9-2d04-45af-85ac-44d16123b548)

- created B1+ map: 
<img width="779" alt="Capture d’écran 2023-09-20 à 18 29 44" src="https://github.com/hMRI-group/hMRI-toolbox/assets/32452352/e27964a1-1cf3-4332-ad92-d64e6aad19ce">

-MPM maps:
![check_maps_001_jet](https://github.com/hMRI-group/hMRI-toolbox/assets/32452352/bda0fd10-c232-4b5c-acbf-2f2113eb7144)

I wonder what could produce this different behavior for the generation of the B1+ maps?

**Comment by lukeje** [comment]
Hi @julfou81,

One thing that comes to mind is that the SE/STE EPI B1 mapping calculation is usually sensitive to the order of the input data, as some metadata for the calculation is usually inferred from the input order. 

In the `Supplementary` subdirectory of the `Results` folder there should be a file called `hMRI_map_creation_b1map_params.json`. Could you check there that the data (in `b1input` and `b0input` are in the same order in both cases? You can also check in that file whether the input parameters were detected correctly in both cases. 

You could also post the contents of the two `hMRI_map_creation_b1map_params.json` files here for me to take a look if you are sure there is no sensitive information stored in the filenames and paths that are stored in there.

**Comment by julfou81** [comment]
Hi @lukeje ,

Thank you very much for your quick answer and your insight: that was indeed what was wrong: the files for the 3D SE/STE image were randomly selected and most of the time not selected in the correct order. 
Corrected this order did indeed solve the problem. Thank you so much, you made my day!
