### ISSUE TITLE
unhandled reference error of fTPM in hmri_create_MTProt.m

### ISSUE THREAD

**Issue by octomike** [hMRI-group/hMRI-toolbox#9]
In cases where we do not have T1w images:

```
INFO: FLASH echoes loaded for each contrast are:
        - MT-weighted: 6 echoes
        - PD-weighted: 8 echoes
        - WARNING: no T1-weighted FLASH echoes available!
```

the creation of hMRI maps results in:

```
25-Feb-2020 15:27:28 - Failed  'Create hMRI maps'
Undefined function or variable 'fTPM'.
In file "[...]toolbox/hMRI/hmri_create_MTProt.m" (???), function "hmri_create_MTProt" at line 941.
In file "[...]toolbox/hMRI/hmri_run_create.m" (???), function "hmri_create_local" at line 131.
In file "[...]toolbox/hMRI/hmri_run_create.m" (???), function "hmri_run_create" at line 21.
```

**Comment by halirutan** [comment]
This appears to be a bug. The creation of `fTPM` [is conditioned](https://gitlab.gwdg.de/cbs-neurophy/hMRI-toolbox-internal/-/blob/master/hmri_create_MTProt.m#L954) on the existence of T1w images and [further down](https://gitlab.gwdg.de/cbs-neurophy/hMRI-toolbox-internal/-/blob/master/hmri_create_MTProt.m#L978), you see that it's actually checked if the variable is defined.

However, the portion [where the error happens](https://gitlab.gwdg.de/cbs-neurophy/hMRI-toolbox-internal/-/blob/master/hmri_create_MTProt.m#L1049-1055) does **not** check again if `fTPM` even exists and thus runs into the error.
